name: Mirror Upstream Repository

on:
  workflow_dispatch:
  schedule:
    # (Every hour)
    - cron:  '7 */1 * * *'

jobs:
  mirror:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        repo:
          - .github
          - .teamcity
          # - branding (empty right now)
          - cache
          - codegen-kt
          - discord-objects
          - docker
          - gradle-tools
          - KETF
          - kord
          - kord-wiki
          - kordx.commands
          - kordx.emoji
          # - kordx.shard (empty right now)
          - ktor
          - Lavalink.kt
          - setup-curl

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.SSH_KEY }}" | base64 -d >> ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_KEY_PUB }}" >> ~/.ssh/id_ed25519.pub

          chmod 0600 ~/.ssh/id_ed25519
          chmod 0644 ~/.ssh/id_ed25519.pub
      
      - name: Trust Codeberg keys
        run: |
          ssh-keyscan -t ed25519 codeberg.org >> ~/.ssh/known_hosts
          ssh-keyscan -t rsa codeberg.org >> ~/.ssh/known_hosts

      - name: Clone upstream repository
        run: git clone --mirror "https://github.com/kordlib/${{ matrix.repo }}.git" repo

      - name: Filter out PR refs
        working-directory: repo
        run: git for-each-ref --format "%(refname)" "refs/pull/*/*" | while read entry; do git update-ref -d "$entry"; done

      - name: Push to target repository
        working-directory: repo
        run: git push --mirror "ssh://git@codeberg.org/kord-mirror/${{ matrix.repo }}.git"
